# GoReleaser configuration for agentx
# Documentation: https://goreleaser.com

version: 2

project_name: agentx

before:
  hooks:
    - go mod tidy

builds:
  - id: agentx
    main: .
    binary: agentx
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/agentsdance/agentx/internal/version.Version={{.Version}}
      - -X github.com/agentsdance/agentx/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/agentsdance/agentx/internal/version.BuildDate={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: agentsdance
    name: agentx
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

brews:
  - name: agentx
    skip_upload: "{{ if .Env.GH_PAT }}false{{ else }}true{{ end }}"
    repository:
      owner: agentsdance
      name: agentx
      token: "{{ .Env.GH_PAT }}"
      pull_request:
        enabled: true
        base: master
    directory: Formula
    homepage: "https://github.com/agentsdance/agentx"
    description: "CLI tool for managing MCP servers and skills across AI coding agents"
    license: "Apache-2.0"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    # This ensures "brew install --HEAD" works
    custom_block: |
      head do
        url "https://github.com/agentsdance/agentx.git", branch: "master"
        depends_on "go" => :build
      end
    install: |
      if build.head?
        system "go", "build", "-ldflags", "-s -w -X github.com/agentsdance/agentx/internal/version.Version=head", "-o", "agentx", "."
      end
      bin.install "agentx"
    test: |
      system "#{bin}/agentx", "--version"
