// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAgents():Promise<Array<main.AgentInfo>>;

export function GetMCPMatrix():Promise<Array<main.MCPStatus>>;

export function GetMCPs(arg1:string):Promise<Array<main.MCPInfo>>;

export function GetPluginsMatrix():Promise<Array<main.PluginStatus>>;

export function GetPluginsRegistry():Promise<Array<main.PluginInfo>>;

export function GetSkillsMatrix():Promise<Array<main.SkillStatus>>;

export function GetSkillsRegistry():Promise<Array<main.SkillInfo>>;

export function GetVersion():Promise<string>;

export function HasMCP(arg1:string,arg2:string):Promise<boolean>;

export function HasPlugin(arg1:string,arg2:string):Promise<boolean>;

export function HasSkill(arg1:string,arg2:string):Promise<boolean>;

export function InstallMCP(arg1:string,arg2:string):Promise<void>;

export function InstallMCPForAgent(arg1:string,arg2:string):Promise<void>;

export function InstallMCPForAll(arg1:string):Promise<void>;

export function InstallPlugin(arg1:string,arg2:string):Promise<void>;

export function InstallPluginForAgent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function InstallPluginForAll(arg1:string,arg2:string):Promise<void>;

export function InstallSkill(arg1:string,arg2:string):Promise<void>;

export function InstallSkillForAgent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function InstallSkillForAll(arg1:string,arg2:string):Promise<void>;

export function RemoveMCP(arg1:string,arg2:string):Promise<void>;

export function RemoveMCPFromAgent(arg1:string,arg2:string):Promise<void>;

export function RemovePlugin(arg1:string,arg2:string):Promise<void>;

export function RemovePluginFromAgent(arg1:string,arg2:string):Promise<void>;

export function RemoveSkill(arg1:string,arg2:string):Promise<void>;

export function RemoveSkillFromAgent(arg1:string,arg2:string):Promise<void>;

export function SupportsPlugins(arg1:string):Promise<boolean>;

export function SupportsSkills(arg1:string):Promise<boolean>;
