// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetMCPMatrix() {
  return window['go']['main']['App']['GetMCPMatrix']();
}

export function GetMCPs(arg1) {
  return window['go']['main']['App']['GetMCPs'](arg1);
}

export function GetPluginsMatrix() {
  return window['go']['main']['App']['GetPluginsMatrix']();
}

export function GetPluginsRegistry() {
  return window['go']['main']['App']['GetPluginsRegistry']();
}

export function GetSkillsMatrix() {
  return window['go']['main']['App']['GetSkillsMatrix']();
}

export function GetSkillsRegistry() {
  return window['go']['main']['App']['GetSkillsRegistry']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HasMCP(arg1, arg2) {
  return window['go']['main']['App']['HasMCP'](arg1, arg2);
}

export function HasPlugin(arg1, arg2) {
  return window['go']['main']['App']['HasPlugin'](arg1, arg2);
}

export function HasSkill(arg1, arg2) {
  return window['go']['main']['App']['HasSkill'](arg1, arg2);
}

export function InstallMCP(arg1, arg2) {
  return window['go']['main']['App']['InstallMCP'](arg1, arg2);
}

export function InstallMCPForAgent(arg1, arg2) {
  return window['go']['main']['App']['InstallMCPForAgent'](arg1, arg2);
}

export function InstallMCPForAll(arg1) {
  return window['go']['main']['App']['InstallMCPForAll'](arg1);
}

export function InstallPlugin(arg1, arg2) {
  return window['go']['main']['App']['InstallPlugin'](arg1, arg2);
}

export function InstallPluginForAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallPluginForAgent'](arg1, arg2, arg3);
}

export function InstallPluginForAll(arg1, arg2) {
  return window['go']['main']['App']['InstallPluginForAll'](arg1, arg2);
}

export function InstallSkill(arg1, arg2) {
  return window['go']['main']['App']['InstallSkill'](arg1, arg2);
}

export function InstallSkillForAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallSkillForAgent'](arg1, arg2, arg3);
}

export function InstallSkillForAll(arg1, arg2) {
  return window['go']['main']['App']['InstallSkillForAll'](arg1, arg2);
}

export function RemoveMCP(arg1, arg2) {
  return window['go']['main']['App']['RemoveMCP'](arg1, arg2);
}

export function RemoveMCPFromAgent(arg1, arg2) {
  return window['go']['main']['App']['RemoveMCPFromAgent'](arg1, arg2);
}

export function RemovePlugin(arg1, arg2) {
  return window['go']['main']['App']['RemovePlugin'](arg1, arg2);
}

export function RemovePluginFromAgent(arg1, arg2) {
  return window['go']['main']['App']['RemovePluginFromAgent'](arg1, arg2);
}

export function RemoveSkill(arg1, arg2) {
  return window['go']['main']['App']['RemoveSkill'](arg1, arg2);
}

export function RemoveSkillFromAgent(arg1, arg2) {
  return window['go']['main']['App']['RemoveSkillFromAgent'](arg1, arg2);
}

export function SupportsPlugins(arg1) {
  return window['go']['main']['App']['SupportsPlugins'](arg1);
}

export function SupportsSkills(arg1) {
  return window['go']['main']['App']['SupportsSkills'](arg1);
}
